services:
    vault:
        public: true
        container_name: vault
        image: <Build ur own image>
        ports:
            - 80:80
        volumes: 
            - /data
        environment:
            - WEBSOCKET_ENABLED=false
            - SIGNUPS_ALLOWED=true
            - WEB_VAULT_ENABLED=true
            - DEST_NAME=<rclone-config-name>
            - BUCKET_NAME=<bucket-name>
            - ENDPOINT=<s3-endpoint>
            - ADMIN_TOKEN=<vaultwarden-admin-token>
            - GPG_PASSPHRASE=<bak-encrypt-passphrase>
            - AWS_ACCESS_KEY=<s3-access-key>
            - AWS_SECRET_KEY=<s3-secret-key>